In [1]:
import numpy as np

In [3]:
x = np.ones((3,4))
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [4]:
print(type(x))

<class 'numpy.ndarray'>


In [5]:
print(x.dtype)

float64


In [14]:
x = np.full((4,3), 9)
print(x)

[[9 9 9]
 [9 9 9]
 [9 9 9]
 [9 9 9]]


In [13]:
x = np.zeros((3,5), dtype= int)
print(x)
print(type(x))
print(x.dtype)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
<class 'numpy.ndarray'>
int32


In [18]:
x = np.eye(5, dtype=int)
print(x)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [19]:
x = np.diag([10,50,102,23,34])
print(x)

[[ 10   0   0   0   0]
 [  0  50   0   0   0]
 [  0   0 102   0   0]
 [  0   0   0  23   0]
 [  0   0   0   0  34]]


In [20]:
x = np.arange(11)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [22]:
x = np.arange(2, 12)
print(x)

[ 2  3  4  5  6  7  8  9 10 11]


In [23]:
x = np.arange(11, 220, 5)
print(x)

[ 11  16  21  26  31  36  41  46  51  56  61  66  71  76  81  86  91  96
 101 106 111 116 121 126 131 136 141 146 151 156 161 166 171 176 181 186
 191 196 201 206 211 216]


In [25]:
# in the cases where non-integer steps are required, it is usually better to use the function np.linspace()
x = np.linspace(2, 6, 20)
print(x)

[2.         2.21052632 2.42105263 2.63157895 2.84210526 3.05263158
 3.26315789 3.47368421 3.68421053 3.89473684 4.10526316 4.31578947
 4.52631579 4.73684211 4.94736842 5.15789474 5.36842105 5.57894737
 5.78947368 6.        ]


In [26]:
x = np.linspace(2, 6, 20, endpoint = False)
print(x)

[2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4 4.6 4.8 5.  5.2 5.4
 5.6 5.8]


In [29]:
# We create a rank 1 ndarray with sequential integers from 0 to 19
x = np.arange(20)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [34]:
# We reshape x into a 4 x 5 ndarray 
x = np.reshape(x, (4,5))
print('Reshaped x = \n', x)

Reshaped x = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [40]:
# We create a 3 x 3 ndarray with random floats in the half-open interval [0.0, 1.0).
X = np.random.random((3,3))
print(X)

[[0.5962666  0.27659169 0.42968497]
 [0.78539    0.20070085 0.83756598]
 [0.41546606 0.98243083 0.07097927]]
